[package]
name = "sacred-zipyip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.107"
sqlite = "0.31.1"
zip = "0.6.6"

[build-dependencies]
cxx-build = "1.0"